### ISSUE TITLE
When estimatedDurationInMinutes isn't set, we still show a duration of 0.

### ISSUE THREAD

**Issue by theClarkSell** [ThatConference/that.us#300]
If the estimatedDurationInMinutes isn't set ( say an older session ), we're showing `0 hours`. In that case we shouldn't show anything. The estimatedDurationInMinutes needs to be at least 1.

test session: http://localhost:5000/sessions/DGHIy8ud1wXgCp5ZZe0k

![image](https://user-images.githubusercontent.com/772569/90913940-9f987f80-e3a2-11ea-8b3a-29d8b2c6200f.png)

Culprit: https://github.com/ThatConference/that.us/blob/master/src/components/sessions/SessionDetails.svelte#L343-L351

**Comment by thalesagapito** [comment]
Is this fixed? If not I could help out

**Comment by zachesposito** [comment]
Hello, it looks like this bug must still exist because although it appears sessions were deprecated in favor of activities, the duration logic seems to be the same:
Duration logic in session details: https://github.com/ThatConference/that.us/blob/7deada831c50cad2fae8bf1b63b30b6ae05bca1a/src/components/sessions/SessionDetails.svelte#L352-L360
Duration logic in activity details: https://github.com/zachesposito/that.us/blob/master/src/_components/activities/ActivityDetails.svelte#L397-L405

Going to go ahead and submit a PR to fix
