### ISSUE TITLE
Activity Search isn't searching beyond the initial load of data

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#774]
**Describe the bug**
Right now it appears our fuzzy search is only searching across the initial load of data.

**To Reproduce**
* goto /activities
* scroll down to load the next result set
* try to search for something in that next result set, like a user's first name

**Expected behavior**
after every loadNext that new additional data should be made available in the potential search 

**Additional context**
I think we need to update the search lib with the new search array after the page loaded.

**Comment by joshpierce** [comment]
Adding to this issue, the sticky header search seems to be having an issue as well.

**To Reproduce**
* goto /activities
* scroll down to load the next result set
* don't scroll back to the top of the page, and type in "Bruno" (second to last speaker on the list)

Currently just getting a sentry crash window instead of the "oops, couldn't find that" message.
